# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

2.5.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hob51hvs/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hob51hvs/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.33.112.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.33.112.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hob51hvs/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-hob51hvs/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a=np.arange(10).reshape(2,5)

memory_size=a.size*a.itemsize
print(memory_size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
import numpy as np
a=np.zeros(10)
a[4]=1


print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import numpy as np
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:

import numpy as np
a=np.arange(10,50)

b=np.flip(a)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
import numpy as np
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
import numpy as np
a=np.array([1,2,0,0,4,0])

b=np.nonzero(a)
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
import numpy as np
a=np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
import numpy as np
a=np.random.random(27).reshape(3,3,3)
a

array([[[0.91750683, 0.0222426 , 0.5846739 ],
        [0.96164605, 0.55765535, 0.4611752 ],
        [0.65099537, 0.54762068, 0.6828973 ]],

       [[0.27320175, 0.0016635 , 0.69212117],
        [0.53059266, 0.81909364, 0.3778722 ],
        [0.841064  , 0.34872698, 0.05202812]],

       [[0.98863453, 0.28609582, 0.85252648],
        [0.67295859, 0.8935163 , 0.53160646],
        [0.36188118, 0.39651373, 0.66658573]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
import numpy as np
a=np.random.random(100).reshape(10,10)

b=a.max()
c=a.min()
print(a)
print(b)
print(c)

[[5.25870200e-01 2.44743565e-01 8.36131692e-03 1.72311042e-02
  9.68762720e-01 5.69252622e-01 1.84945618e-01 3.39840894e-02
  6.90067160e-01 9.40350734e-01]
 [4.51677476e-01 8.75280708e-01 9.02517584e-01 4.08149423e-01
  4.25266954e-01 5.56255866e-01 9.67662119e-01 4.32563353e-02
  2.37475104e-01 7.49374993e-01]
 [9.01673099e-01 4.40314674e-01 9.28111628e-01 8.81780887e-02
  9.92927311e-01 6.85697129e-01 7.39483094e-02 3.11385570e-01
  3.82201371e-02 7.10787147e-01]
 [8.40819459e-01 9.08576905e-01 9.20096424e-01 9.35751487e-01
  1.84528775e-01 9.31707982e-01 7.46909359e-01 4.56670638e-02
  9.19105441e-01 3.29254332e-01]
 [5.36542794e-01 9.03531537e-01 5.06802583e-01 2.50343811e-01
  1.51535010e-02 9.59694543e-01 9.99609949e-01 7.41146782e-01
  7.29897282e-01 7.66202123e-01]
 [4.69912058e-01 8.12454539e-02 5.52547312e-01 8.77822331e-01
  9.15133411e-01 5.30778385e-01 9.53291442e-01 4.56567758e-01
  7.43902517e-01 2.39038083e-01]
 [6.99187382e-01 8.63403128e-01 7.97628620e-01 1.42831716e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
import numpy as np
a=np.random.random(30)
b=a.mean()
print(a)
print(b)

[0.55206657 0.91650335 0.28008641 0.61139962 0.38176137 0.70379587
 0.7588113  0.07544932 0.93942066 0.5301609  0.34291972 0.24491286
 0.60574141 0.76406758 0.27159684 0.26369229 0.03694856 0.2176001
 0.76450186 0.60104744 0.22469674 0.69294718 0.85616253 0.88061097
 0.86064397 0.69291012 0.25276962 0.30658386 0.97050814 0.38679308]
0.532903674298645


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
import numpy as np
a=np.ones((5,5))
a[1:-1,1:-1]=0#a[row_slicing,col_slicing]1=start,-1=end-1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
z=np.ones((3,3))
z_border=np.zeros((5,5))

z_border[1:-1,1:-1]=z

print(z_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan) #nan
print(np.nan == np.nan)#false
print(np.inf > np.nan) #false
print(np.nan - np.nan) #nan
print(np.nan in set([np.nan])) #true
print(0.3 == 3 * 0.1) #false

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
import numpy as np
a=np.diag([1,2,3,4],k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
import numpy as np
z=np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
import numpy as np
index=np.unravel_index(99,(6,7,8))

print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
base_b=np.array([[0,1],[1,0]])

checkerboard=np.tile(base_b,(4,4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
z=np.random.random((5,5))
zmax=z.max()
zmin=z.min()

z_normalize=(z-zmin)/(zmax-zmin)
print(z_normalize)

[[0.44047808 0.60179313 0.86680575 0.4329159  0.7465375 ]
 [0.02247018 0.65577282 0.54331379 0.38127587 0.17284503]
 [0.99033929 1.         0.05412954 0.62023246 0.92478653]
 [0.23052728 0.27030556 0.5302569  0.81258401 0.05335894]
 [0.64070201 0.         0.07456989 0.60692192 0.03849491]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
a=np.dtype([('R','u1'),('G','u1'),('B','u1'),('A','u1')])
print(a)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:

a=np.arange(1,16).reshape(5,3)
b=np.arange(1,7).reshape(3,2)

multi=np.dot(a,b)
print(multi)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a=np.arange(1,10)
a[(a>=3) & (a<=8)]*=-1
print(a)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

# The answer is:

```
Legal expressions: Z**Z, 2 << Z >> 2, Z <- Z, 1j*Z, Z/1/1

Illegal expression: Z<Z>Z (Raises a ValueError)
```


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
# Result:
# 1. nan
# 2. 0
# 3. [-9.22337204e+18] 


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
import numpy as np
a=np.array([-3.4,-1,1.0,0,3.3,1.4,5.9])

output=np.copysign(np.ceil(np.abs(a)),a)

print(output)

[-4. -1.  1.  0.  4.  2.  6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
import numpy as np
a=np.arange(20,40).reshape(5,4)
b=np.arange(30,50).reshape(5,4)
print(a)
print(b)
result=np.intersect1d(a,b)
print(result)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]
[30 31 32 33 34 35 36 37 38 39]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
import numpy as np

a=np.seterr(all='ignore')

print(a)

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
#false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
import numpy as np

today=np.datetime64('today','D')
yesterday=today-np.timedelta64(1,'D')
tomorrow=today+np.timedelta64(1,'D')

print(today)
print(yesterday)
print(tomorrow)

2026-07-10
2026-07-09
2026-07-11


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
import numpy as np
july=np.arange('2016-07','2016-08',dtype='datetime64[D]')

print(f"July 2016:{july}")

July 2016:['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
import numpy as np

A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
np.add(A, B, out=B)  
np.multiply(A, -0.5, out=A)
np.multiply(A, B, out=A)

print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
import numpy as np
a=np.random.uniform(0,10,10)

#m=Method
m1=a.astype(int)
m2=a//1
m3=np.floor(a)
m4=np.trunc(a)
print(m1)
print(m2)
print(m3)
print(m4)

[0 9 0 8 6 1 2 3 6 3]
[0. 9. 0. 8. 6. 1. 2. 3. 6. 3.]
[0. 9. 0. 8. 6. 1. 2. 3. 6. 3.]
[0. 9. 0. 8. 6. 1. 2. 3. 6. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
import numpy as np
a=np.zeros((5,5)) + np.arange(5)

print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
import numpy as np

def generator_function():
  for x in range(10):
    yield x

a=np.fromiter(generator_function(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
import numpy as np

a=np.linspace(0,1,12,endpoint=True)[1:-1]

print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
import numpy as np
a=np.random.random(10)
sort_a=np.sort(a)

print(sort_a)

[0.00299073 0.11419963 0.12273064 0.13310275 0.15536144 0.38847257
 0.70006486 0.75495751 0.79742902 0.94741572]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [40]:
import numpy as np
a=np.array([1,2,3])

res_of_sum=np.add.reduce(a) 

print(res_of_sum)

6


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [41]:
import numpy as np

a=np.random.random(5)
b=np.random.random(5)
c=np.array_equal(a,b)
print(c)



False


#### 43. Make an array immutable (read-only) (★★☆)

In [42]:
import numpy as np

a=np.array([2,3,45,6,34])
a.flags.writeable=False
a[0]=5 # No change in arr
print(a)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]

R=np.sqrt(x**2 + y**2)

t=np.arctan2(y,x)

print("Cartesian Matrix (Z):\n", a)
print("-" * 40)
print("Radius (R):\n", R)
print("-" * 40)
print("Angle (Theta in Radians):\n", t)


Cartesian Matrix (Z):
 [[0.1575471  0.45695087]
 [0.66344064 0.72072034]
 [0.24117329 0.27987074]
 [0.31033525 0.63221737]
 [0.37961241 0.42987312]
 [0.10698679 0.50055498]
 [0.17460114 0.05416286]
 [0.44633791 0.34466966]
 [0.04683386 0.62607161]
 [0.29170495 0.84630646]]
----------------------------------------
Radius (R):
 [0.48334789 0.9795873  0.36944849 0.70427748 0.57349497 0.51186079
 0.18280911 0.56392793 0.62782089 0.89516836]
----------------------------------------
Angle (Theta in Radians):
 [1.2387802  0.82675682 0.85953112 1.114481   0.84740826 1.36022831
 0.30079641 0.65756894 1.49612947 1.23886873]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np
a=np.random.random(10)
a[a.argmax()]=0

print(a)

[0.30907275 0.         0.97019548 0.0587817  0.67504629 0.52442041
 0.39021007 0.33428086 0.93265569 0.65728658]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np

x=np.linspace(0,1,5)
y=np.linspace(0,1,5)

X,Y=np.meshgrid(x,y)

s_dtype=[('x','f4'),('y','f4')] #f4= 32-bit Float

z=np.zeros(X.shape,dtype=s_dtype)

z['x']=X
z['y']=Y

print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

X=np.array([1,2,3,4,7])
Y=np.array([5,6,7])

denom=X[:,np.newaxis]-Y

C=1.0/denom

print(C)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]
 [ 0.5         1.                 inf]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [ ]:
import numpy as np


print("--- Integer Limits ---")
print(f"int8   -> Min: {np.iinfo(np.int8).min}, Max: {np.iinfo(np.int8).max}")
print(f"int32  -> Min: {np.iinfo(np.int32).min}, Max: {np.iinfo(np.int32).max}")
print(f"int64  -> Min: {np.iinfo(np.int64).min}, Max: {np.iinfo(np.int64).max}")

print("\n--- Floating Point Limits ---")
print(f"float32 -> Min: {np.finfo(np.float32).min}, Max: {np.finfo(np.float32).max}")
print(f"float64 -> Min: {np.finfo(np.float64).min}, Max: {np.finfo(np.float64).max}")


--- Integer Limits ---
int8   -> Min: -128, Max: 127
int32  -> Min: -2147483648, Max: 2147483647
int64  -> Min: -9223372036854775808, Max: 9223372036854775807

--- Floating Point Limits ---
float32 -> Min: -3.4028234663852886e+38, Max: 3.4028234663852886e+38
float64 -> Min: -1.7976931348623157e+308, Max: 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy as np
np.set_printoptions(threshold=np.inf)
a=np.arange(1000)
print(a)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
import numpy as np
a=np.random.uniform(0,10,10)
print(a)

target_scalar=5.3
print(target_scalar)

closest_index=np.abs(a-target_scalar).argmin()
closest_value=a[closest_index]

print(closest_index)
print(closest_value)


[0.44308024 8.94588733 8.92575733 7.54130548 9.22905666 1.28198426
 6.35819197 0.57004247 9.44115162 4.97045043]
5.3
9
4.970450426811953


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np

dt=[
  ('position',[('x',float),
               ('y',float)]),
  ('color',[('r',int),
            ('g',int),
            ('b',int)])             
]

a=np.zeros(10,dtype=dt)

#print(a)

a['position']['x'][0] = 20
a

array([((20., 0.), (0, 0, 0)), (( 0., 0.), (0, 0, 0)),
       (( 0., 0.), (0, 0, 0)), (( 0., 0.), (0, 0, 0)),
       (( 0., 0.), (0, 0, 0)), (( 0., 0.), (0, 0, 0)),
       (( 0., 0.), (0, 0, 0)), (( 0., 0.), (0, 0, 0)),
       (( 0., 0.), (0, 0, 0)), (( 0., 0.), (0, 0, 0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<i8'), ('g', '<i8'), ('b', '<i8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import numpy as np

a=np.random.random((100,2))
X,Y=a[:,0],a[:,1]

D=np.sqrt((X-X[:,np.newaxis]) **2 + (Y -Y[:,np.newaxis])**2)

print(D)
print(D.shape)


[[0.         0.4491299  0.68829006 ... 0.76947698 0.11237969 0.52963012]
 [0.4491299  0.         0.57766164 ... 0.33804833 0.5492723  0.13755665]
 [0.68829006 0.57766164 0.         ... 0.5733778  0.79055823 0.70696718]
 ...
 [0.76947698 0.33804833 0.5733778  ... 0.         0.87619027 0.35509048]
 [0.11237969 0.5492723  0.79055823 ... 0.87619027 0.         0.61635926]
 [0.52963012 0.13755665 0.70696718 ... 0.35509048 0.61635926 0.        ]]
(100, 100)


#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [ ]:
import numpy as np

a=np.arange(10,dtype=np.float32)

print(a,a.dtype)

a.view(np.int32)[...]=a

print(a.view(np.int32))
print(a.view(np.int32).dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float32
[0 1 2 3 4 5 6 7 8 9]
int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np
from io import StringIO

file=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")

A=np.genfromtxt(file,delimiter=",")

print(A)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
import numpy as np

a=np.array([[1,2],
            [3,4]])

for index,value in np.ndenumerate(a):
  print(f"Index {index},Value {value}")

Index (0, 0),Value 1
Index (0, 1),Value 2
Index (1, 0),Value 3
Index (1, 1),Value 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
import numpy as np

size=4
mu=0.0
sigma=1.0

x=np.linspace(-1,1,size)
y=np.linspace(-1,1,size)

X,Y=np.meshgrid(x,y)

d=x**2 + y**2
gaussian=np.exp(-((d - mu) / (2.0 * sigma ** 2)))

print(gaussian)

[0.36787944 0.89483932 0.89483932 0.36787944]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
import numpy as np
n=5
p=2
val_of_place=78

z=np.zeros((n,n))

indices=np.random.choice(range(n*n),p,replace=False)

np.put(z,indices,val_of_place)

print(z)


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 78.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 78.  0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
import numpy as np

x=np.arange(4,3)

Y=X - X.mean(axis=1,keepdims=True)

print(Y)

[[-1.         -0.33333333  0.33333333  1.        ]
 [-1.         -0.33333333  0.33333333  1.        ]
 [-1.         -0.33333333  0.33333333  1.        ]
 [-1.         -0.33333333  0.33333333  1.        ]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
import numpy as np
a=np.array([[1,4,3],[4,5,6],[9,6,8]])

n=2
sorted=a[:,n].argsort()

result=a[sorted]

print(sorted)

[0 1 2]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
import numpy as np
Z = np.array([[1, 0, 3],
              [4, 0, 6],
              [7, 0, 1]])

has_null=(~Z.any(axis=0)).any()

print(has_null)

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np

a=np.array([10,11,12,17,15,18,24])
target=20

idx=(np.abs(a - target)).argmin()

a[idx]

np.int64(18)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
import numpy as np

A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)

it=np.nditer([A,B,None])

for x,y,z in it:
  z[...] = x+y

result=it.operands[2]

result


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
import numpy as np

class NameArray(np.ndarray):
  def __new__(cls,input_array,name="Named Array"):
    obj=np.asarray(input_array).view(cls)
    obj.name=name 
    return obj
  
  def __array_finalize__(self, obj):
    if obj is None: return

    self.name=getattr(obj,'name',"Named Array")

z=NameArray(np.arange(5), name="My_Vector")
z.name
z

NameArray([0, 1, 2, 3, 4])

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
import numpy as np
a=np.ones(5)
b=np.array([0,1,2,3,4,1])

np.add.at(a,b,1)

b

array([0, 1, 2, 3, 4, 1])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
import numpy as np

X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([1, 3, 1, 2, 3, 1])

add=np.bincount(I, weights=X)

add

array([ 0., 10.,  4.,  7.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
import numpy as np

w,h=16,16
I = np.random.randint(0,4,(w,h,3)).astype(np.ubyte)

c=I.reshape(-1,3)

Unique_c=np.unique(c , axis=0)

result=len(c)
print(result)

256


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np

a=np.random.randint(0,10,(3,4,5,5))

sum_last_two=a.sum(axis=(-2,-1))

print(a.shape)
print(sum_last_two)

(3, 4, 5, 5)
[[119 132 138 112]
 [ 88 127 107 103]
 [115 106 134 118]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
import numpy as np

D = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
S = np.array([0, 1, 0, 2, 1, 0])

sub_sum=np.bincount(S,weights=D)
sub_count=np.bincount(S)
sub_mean=sub_sum / sub_count

print(sub_mean)

[3.33333333 3.5        4.        ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
import numpy as np

A = np.random.randint(0, 10, (3, 3))
B = np.random.randint(0, 10, (3, 3))

diag_met1 = np.einsum("ij,ji->i", A, B)
diag_met2=np.sum(A*B.T,axis=1)

print(diag_met1)
print(diag_met2)

[ 38  22 114]
[ 38  22 114]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5])
nz = 3

new_Z = np.zeros(len(Z) + (len(Z) - 1) * nz, dtype=Z.dtype)

new_Z[::nz+1] = Z

print(new_Z)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [ ]:
import numpy as np
a=np.ones([5,5,3])
b=np.zeros([5,5])

B=b[:,:,np.newaxis]

result=a*B

print(result)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

a[[0,2]] = a[[2,0]]

a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
import numpy as np

np.random.seed(42)
triangle=np.random.randint(0,10,size=(10,3))

f=np.repeat(triangle,3,axis=0)
f=f.reshape(-1,3)

edges=np.roll(f,-1,axis=1)[:,1:]

line=np.vstack([triangle[:,[0,1]],triangle[:,[1,2]],triangle[:,[2,0]]])

line=np.sort(line,axis=0)

u_line=np.unique(line,axis=0)

print(len(u_line))
print(u_line)

10
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
import numpy as np

C=np.array([2,3,1,5,0,3])

a_index=np.arange(len(C))

a=np.repeat(a_index,C)
b=np.bincount(a)
print(a)
print(b)
print(np.array_equal((b),C))

[0 0 1 1 1 2 3 3 3 3 3 5 5 5]
[2 3 1 5 0 3]
True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
import numpy as np
def window_aveg(arr,n):
  cumsum=np.cumsum(arr)
  cumsum[n:] = cumsum[n:] - cumsum[:-n]
  return cumsum[n -1:] / n

a=np.array([20,30,1,33,53,21])
n=3

result=window_aveg(a,n)

print(a)
print(result)

[20 30  1 33 53 21]
[17.         21.33333333 29.         35.66666667]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([10,20,30,40,50,60,70,80])

result=sliding_window_view(Z,window_shape=3)

print(result)

[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
import numpy as np

A = np.array([True,False,False,True,True,True,False,False])
B = np.array([1.4,-4.2,5.2,-3.4,9.1,-3.6,-1.0])

result1 = np.logical_not(A, out=A)
result2 = np.negative(B,out=B)

print(result1)
print(result2)


[False  True  True False False False  True  True]
[-1.4  4.2 -5.2  3.4 -9.1  3.6  1. ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np

p = np.array([1,5])
p0 = np.array([[0,0],[1,2],[2,3]])
p1 = np.array([[1,1],[4,2],[3,8]])

v = p1 - p0
w = p - p0

cross = np.abs(v[:,0] * w[:,1] - v[:,1] * v[:,0])
length = np.sqrt(np.sum(v**2 , axis=1))
distances = cross / length

print(distances)

[2.82842712 3.         0.58834841]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np


P0 = np.array([[0, 0], [1, 2], [2, 3]])
P1 = np.array([[1, 1], [4, 6], [5, 8]])

P = np.array([[1, 5], [0, 2]])

v = P1 - P0


w = P[:, np.newaxis, :] - P0[np.newaxis, :, :] 


cross_product = np.abs(v[np.newaxis, :, 0] * w[:, :, 1] - v[np.newaxis, :, 1] * w[:, :, 0])

line_length = np.sqrt(np.sum(v**2, axis=1))


distances = cross_product / line_length[np.newaxis, :]

print(distances)

[[2.82842712 1.8        1.88648444]
 [1.41421356 0.8        1.2004901 ]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
import numpy as np

def extract_subpart( z , center , tar_shape , fill=0):
  result = np.full(tar_shape, fill_value=fill, dtype=z.dtype)
  r_offset = tar_shape[0] // 2
  c_offset = tar_shape[1] // 2
  z_r_start = max(0, center[0] - r_offset)
  z_r_end   = min(z.shape[0], center[0] + r_offset + 1)
  z_c_start = max(0, center[1] - c_offset)
  z_c_end   = min(z.shape[1], center[1] + c_offset + 1)
  res_r_start = z_r_start - (center[0] - r_offset)
  res_r_end   = res_r_start + (z_r_end - z_r_start)
  res_c_start = z_c_start - (center[1] - c_offset)
  res_c_end   = res_c_start + (z_c_end - z_c_start)
  result[res_r_start:res_r_end, res_c_start:res_c_end] = z[z_r_start:z_r_end, z_c_start:z_c_end]
  return result

z=np.arange(1,26).reshape(5,5)
cropped = extract_subpart(z, center=(0, 0), tar_shape=(3, 3), fill=0)

print(z)
print(cropped)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[0 0 0]
 [0 1 2]
 [0 6 7]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

R = sliding_window_view(Z,window_shape=4)

R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [ ]:
import numpy as np

z = np.array([[1,2,3],[3,4,5],[5,6,7]])

rank = np.linalg.matrix_rank(z)

print(z)
print(rank)

[[1 2 3]
 [3 4 5]
 [5 6 7]]
2


#### 83. How to find the most frequent value in an array?

In [ ]:
import numpy as np

a=np.array([1,2,3,4,5,6,7,3,7,0,3,1,7,4,4,5,8,9])

count = np.bincount(a)
most_freq = np.argmax(count)

print(a)
print(most_freq)

[1 2 3 4 5 6 7 3 7 0 3 1 7 4 4 5 8 9]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view
A = np.random.randint(0,10,(10,10))
block = sliding_window_view(A, window_shape=(3,3))

print(A.shape)
print(block.shape)



(10, 10)
(8, 8, 3, 3)


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __setitem__(self, index, value):
        if isinstance(index, tuple) and len(index) == 2:
            i, j = index
            super().__setitem__((i, j), value)
            super().__setitem__((j, i), value)
        else:
            super().__setitem__(index, value)

def symmetric_array(shape, dtype=float):
    return np.zeros(shape, dtype=dtype).view(SymmetricArray)

Z = symmetric_array((3, 3))

print( Z)
Z[0, 2] = 99
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0. 99.]
 [ 0.  0.  0.]
 [99.  0.  0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
import numpy as np

p = 3
q = 3

matrices = np.arange(1,p*q*q+1).reshape(p,q,q)
vector = np.array([1,2,3]).reshape(p,1)
vector = np.arange(1,p*q+1).reshape(p,q,1)

result = np.einsum('pij,pjk->ik',matrices,vector)

print(result)



[[663]
 [798]
 [933]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
import numpy as np
a = np.ones((16,16))
Z = a.reshape(4,4,4,4).sum(axis=(1,3))

print(Z)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
import numpy as np

def game_of_life_step(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2]                 + Z[1:-1, 2:] +
         Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])

    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.zeros((10, 10), dtype=int)
Z[1, 2] = 1
Z[2, 3] = 1
Z[3, 1:4] = 1

print("Generation 0:")
print(Z)

Z = game_of_life_step(Z)
print("\nGeneration 1:")
print(Z)

Generation 0:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Generation 1:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
import numpy as np

A = np.arange(100)
np.random.shuffle(A)

n = 5

largest = np.argpartition(-A,n)[:n]

print(A[largest])

[99 98 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [ ]:
import numpy as np

def cartesian_product(arrays):
    grid = np.meshgrid(*arrays, indexing='ij')
    stacked = np.stack(grid, axis=-1)
    return stacked.reshape(-1, len(arrays))
v1 = np.array([1, 2])
v2 = np.array([3, 4, 5])
v3 = np.array([6])

result = cartesian_product([v1, v2, v3])

print(result)

[[1 3 6]
 [1 4 6]
 [1 5 6]
 [2 3 6]
 [2 4 6]
 [2 5 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
import numpy as np
regular_arr = np.array([(1, "Rakesh"), (2, "Amit"), (3, "Joy")], dtype=[('id', 'i4'), ('name', 'U10')])

recoed_arr = np.rec.array(regular_arr)

print(recoed_arr)

print(recoed_arr.name)

print(recoed_arr.id)


[(1, 'Rakesh') (2, 'Amit') (3, 'Joy')]
['Rakesh' 'Amit' 'Joy']
[1 2 3]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
import numpy as np

A = np.random.rand(1000)

m1 = A**3
m2 = np.power(A,3)
m3 = A * A * A

print(m1)
print(m2)
print(m3)

[1.80018238e-06 9.96049360e-03 1.10730424e-01 1.77323682e-06
 2.40330503e-03 3.08796302e-03 3.28625951e-01 1.48850656e-03
 3.67000001e-07 3.87323724e-02 2.07401839e-03 5.65208305e-03
 4.03259737e-01 7.49902811e-01 7.18253530e-03 1.52498418e-02
 4.97188457e-01 1.20494252e-01 6.87722662e-02 2.10002951e-01
 1.46042557e-02 3.76133582e-02 1.68785836e-01 9.87899722e-01
 5.86315366e-01 3.40312940e-02 1.38767501e-01 2.85271125e-02
 3.00705745e-01 5.42014342e-01 4.25501210e-03 4.83079319e-01
 1.75575975e-01 1.12563239e-01 8.31205060e-03 6.09680905e-02
 4.92068628e-03 7.50487480e-03 5.16011738e-01 4.42239560e-02
 4.02624988e-01 9.95748806e-02 8.50803444e-02 4.83126516e-01
 3.45552351e-02 4.23350276e-01 1.07743908e-02 1.10150824e-01
 5.62996450e-01 7.01135020e-01 1.09095000e-01 2.33830543e-01
 7.66981331e-02 2.16964631e-01 1.00978483e-01 4.79994641e-01
 5.74906133e-01 9.69806633e-02 1.82994130e-02 5.95529441e-01
 2.18403734e-01 3.51288910e-01 1.36131224e-02 6.74395163e-03
 1.00437060e-02 7.687355

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [1, 4, 7],
              [2, 3, 5],
              [3, 1, 2], 
              [9, 0, 1],
              [8, 2, 3]]) 
B = np.array([[1, 2],
              [3, 1]])

mask = [np.isin(A,row).any(axis=1) for row in B]
masks = np.logical_and.reduce(mask)
row_of_A = A[masks]

print(row_of_A)

[[1 2 3]
 [1 4 7]
 [2 3 5]
 [3 1 2]
 [9 0 1]
 [8 2 3]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
import numpy as np
M = np.array([[1, 1, 1],[2, 2, 3],[5, 5, 5],[4, 2, 4],[7, 7, 7],[1, 2, 3],[0, 0, 0],[8, 8, 9],[3, 3, 3],[6, 5, 4]])

mask = ~np.all(M[:,1:] == M[:,:1],axis=1)

unequal_val = M[mask]

print(unequal_val)

[[2 2 3]
 [4 2 4]
 [1 2 3]
 [8 8 9]
 [6 5 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
import numpy as np

a = np.array([1,0,2,3,23,45,123],dtype = np.uint8)

bits = np.arange(8)[::-1]
binary = (a[:,None] >> bits) & 1

print(a)
print(binary)

[  1   0   2   3  23  45 123]
[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 1 0 1 1 1]
 [0 0 1 0 1 1 0 1]
 [0 1 1 1 1 0 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [43]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[1,2,3],[6,7,8],[4,5,6],[0,9,8],[4,5,8]])

np.unique(A,axis=0)

array([[0, 9, 8],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 8],
       [6, 7, 8]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [46]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

print("Sum :",np.einsum('i->',a))
print("Mul :",np.einsum('i,i->i',a,b))
print("Inner :",np.einsum('i,i->',a,b))
print("Outer :",np.einsum('i,j->ij',a,b))




Sum : 10
Mul : [ 4 10 18 28]
Inner : 60
Outer : [[ 4  5  6  7]
 [ 8 10 12 14]
 [12 15 18 21]
 [16 20 24 28]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [48]:
import numpy as np

phi = np.arange(0, 10 * np.pi, 0.1)
x = phi * np.cos(phi)
y = phi * np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**0.5

r = np.zeros_like(x)
r[1:] = np.cumsum(dr)

r_int = np.linspace(0, r.max(), 200)

x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

print( x_int[:5])

[ 0.         -0.37313123 -2.59817608 -3.2621205  -2.18442687]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [50]:
import numpy as np

x = np.array([[1.0,2.0,3.0,4.0],[2.0,5.0,0.0,1.0],[0.0,9.0,5.0,3.0]])
n = 4

is_int = np.all(np.mod(x,1) == 0, axis=1)
sum_in_n = np.sum(x,axis=1) == n
result = x[is_int & sum_in_n]

print(result)

[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [51]:
import numpy as np

x = np.random.randn(100)
n= 1000

idx = np.random.randint(0,x.size,(n,x.size))
means = x[idx].mean(axis=1)
confidence_int = np.percentile(means,[2.5,97.5])

print(confidence_int)

[-0.06553123  0.28256678]
