# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

2.4.6
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zj20k55h/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zj20k55h/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.188.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.188.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zj20k55h/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-zj20k55h/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
a=np.arange(10).reshape(2,5)

memory_size=a.size*a.itemsize
print(memory_size)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
import numpy as np
a=np.zeros(10)
a[4]=1


print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
import numpy as np
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
np.flip(a)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
import numpy as np
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
import numpy as np
a=np.array([1,2,0,0,4,0])

b=np.nonzero(a)
print(b)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
import numpy as np
a=np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
import numpy as np
a=np.random.random(27).reshape(3,3,3)
a

array([[[0.13530332, 0.35560614, 0.04427772],
        [0.9175626 , 0.06194259, 0.06003045],
        [0.73785209, 0.72998705, 0.01124029]],

       [[0.92378737, 0.78655601, 0.77234056],
        [0.27635051, 0.46814147, 0.18172094],
        [0.3329168 , 0.20339902, 0.36706035]],

       [[0.60330556, 0.86766158, 0.52669413],
        [0.89654763, 0.21423684, 0.75083832],
        [0.46713496, 0.56060145, 0.80388925]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
import numpy as np
a=np.random.random(100).reshape(10,10)

b=a.max()
c=a.min()
print(a)
print(b)
print(c)

[[0.63008105 0.32879004 0.56675959 0.94178306 0.57673046 0.74425074
  0.81706335 0.40659709 0.87860823 0.48601603]
 [0.85606077 0.00390186 0.07344427 0.99648161 0.19544427 0.86368725
  0.1304434  0.36090449 0.30008633 0.15359471]
 [0.61299288 0.681212   0.55673175 0.49969529 0.17270692 0.30858725
  0.0912568  0.85220091 0.87895744 0.94718148]
 [0.17790595 0.79529241 0.89188818 0.44379927 0.65645206 0.42172978
  0.3601709  0.92764427 0.57439279 0.50582045]
 [0.76637439 0.0391597  0.28586635 0.25181094 0.94080086 0.72788924
  0.43736862 0.25844471 0.34233523 0.6489369 ]
 [0.22138785 0.60044193 0.33997511 0.28693324 0.85426286 0.69606983
  0.00334988 0.08039134 0.63190277 0.46348685]
 [0.2556423  0.21426568 0.82793562 0.66990961 0.89152728 0.32557193
  0.19815145 0.96246752 0.10158445 0.6054394 ]
 [0.95084218 0.81163049 0.40304926 0.37596722 0.0417045  0.03573642
  0.11794178 0.98061838 0.19967656 0.61248369]
 [0.68885485 0.43801157 0.68366422 0.09676136 0.63699608 0.35403746
  0.6129517 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
import numpy as np
a=np.random.random(30)
b=a.mean()
print(a)
print(b)

[0.80421996 0.21949921 0.90929704 0.15521317 0.48191857 0.92102434
 0.17612604 0.54285573 0.06180203 0.81654342 0.76923351 0.48854314
 0.20248991 0.26550646 0.60348487 0.67858648 0.83183972 0.41993338
 0.6579804  0.37149461 0.45263569 0.60616787 0.60105596 0.70049422
 0.52530659 0.11950718 0.43383735 0.12857155 0.85613065 0.09125961]
0.49641862242986107


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
import numpy as np
a=np.ones((5,5))
a[1:-1,1:-1]=0#a[row_slicing,col_slicing]1=start,-1=end-1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
z=np.ones((3,3))
z_border=np.zeros((5,5))

z_border[1:-1,1:-1]=z

print(z_border)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan) #nan
print(np.nan == np.nan)#false
print(np.inf > np.nan) #false
print(np.nan - np.nan) #nan
print(np.nan in set([np.nan])) #true
print(0.3 == 3 * 0.1) #false

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a=np.diag([1,2,3,4],k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
z=np.zeros((8,8))
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
index=np.unravel_index(99,(6,7,8))

print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
base_b=np.array([[0,1],[1,0]])

checkerboard=np.tile(base_b,(4,4))

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
z=np.random.random((5,5))
zmax=z.max()
zmin=z.min()

z_normalize=(z-zmin)/(zmax-zmin)
print(z_normalize)

[[0.85459945 0.07457774 0.175023   0.11918249 0.66292124]
 [0.24293827 0.38570082 0.03923083 0.12427594 0.09585472]
 [0.08104594 1.         0.88641071 0.89011275 0.02178002]
 [0.         0.3958791  0.83901587 0.75362391 0.85597597]
 [0.9851286  0.48819912 0.39003977 0.75940257 0.33544823]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
a=np.dtype([('R','u1'),('G','u1'),('B','u1'),('A','u1')])
print(a)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:

a=np.arange(1,16).reshape(5,3)
b=np.arange(1,7).reshape(3,2)

multi=np.dot(a,b)
print(multi)

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
a=np.arange(1,10)
a[(a>=3) & (a<=8)]*=-1
print(a)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

# The answer is:

```
Legal expressions: Z**Z, 2 << Z >> 2, Z <- Z, 1j*Z, Z/1/1

Illegal expression: Z<Z>Z (Raises a ValueError)
```


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
# Result:
# 1. nan
# 2. 0
# 3. [-9.22337204e+18] 


#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
import numpy as np
a=np.array([-3.4,-1,1,0,3,14])

output=np.copysign(np.ceil(np.abs(a)),a)

print(output)

[-4. -1.  1.  0.  3. 14.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
import numpy as np
a=np.array([1,3,4,2,5])
b=np.array([4,2,5,7,4])

result=np.intersect1d(a,b)
print(result)

[2 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
import numpy as np

a=np.seterr(all='ignore')

print(a)

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
#false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
import numpy as np

today=np.datetime64('today','D')
yesterday=today-np.timedelta64(1,'D')
tomorrow=today+np.timedelta64(1,'D')

print(today)
print(yesterday)
print(tomorrow)

2026-06-21
2026-06-20
2026-06-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
import numpy as np
july=np.arange('2016-07','2016-08',dtype='datetime64[D]')

print(july)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
import numpy as np

A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
np.add(A, B, out=B)  
np.multiply(A, -0.5, out=A)
np.multiply(A, B, out=A)

print(A)

[ -2.5  -7.  -13.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [35]:
import numpy as np
a=np.random.uniform(0,10,10)

#m=Method
m1=a.astype(int)
m2=a//1
m3=np.floor(a)
m4=np.trunc(a)
print(m1)
print(m2)
print(m3)
print(m4)

[7 0 9 4 4 5 8 9 7 9]
[7. 0. 9. 4. 4. 5. 8. 9. 7. 9.]
[7. 0. 9. 4. 4. 5. 8. 9. 7. 9.]
[7. 0. 9. 4. 4. 5. 8. 9. 7. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
import numpy as np
a=np.zeros((5,5)) + np.arange(5)

print(a)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [37]:
import numpy as np

def generator_function():
  for x in range(10):
    yield x

a=np.fromiter(generator_function(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
import numpy as np

a=np.linspace(0,1,12,endpoint=True)[1:-1]

print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
import numpy as np
a=np.random.random(10)
sort_a=np.sort(a)

print(sort_a)

[0.12538226 0.27511798 0.28314772 0.39026113 0.48291028 0.55641628
 0.57389579 0.58846813 0.66321106 0.98994377]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [45]:
import numpy as np
a=np.array([1,2,3])

res_of_sum=np.add.reduce(a) 

print(res_of_sum)

6


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [47]:
import numpy as np

a=np.random.random(5)
b=np.random.random(5)
c=np.array_equal(a,b)
print(c)



False


#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
import numpy as np

a=np.array([2,3,45,6,34])
a.flags.writeable=False
a[0]=5
print(a)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [60]:
import numpy as np
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]

R=np.sqrt(x**2 + y**2)

t=np.arctan2(y,x)

print("Cartesian Matrix (Z):\n", a)
print("-" * 40)
print("Radius (R):\n", R)
print("-" * 40)
print("Angle (Theta in Radians):\n", t)


Cartesian Matrix (Z):
 [[0.1575471  0.45695087]
 [0.66344064 0.72072034]
 [0.24117329 0.27987074]
 [0.31033525 0.63221737]
 [0.37961241 0.42987312]
 [0.10698679 0.50055498]
 [0.17460114 0.05416286]
 [0.44633791 0.34466966]
 [0.04683386 0.62607161]
 [0.29170495 0.84630646]]
----------------------------------------
Radius (R):
 [0.48334789 0.9795873  0.36944849 0.70427748 0.57349497 0.51186079
 0.18280911 0.56392793 0.62782089 0.89516836]
----------------------------------------
Angle (Theta in Radians):
 [1.2387802  0.82675682 0.85953112 1.114481   0.84740826 1.36022831
 0.30079641 0.65756894 1.49612947 1.23886873]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [61]:
import numpy as np
a=np.random.random(10)
a[a.argmax()]=0

print(a)

[0.30907275 0.         0.97019548 0.0587817  0.67504629 0.52442041
 0.39021007 0.33428086 0.93265569 0.65728658]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)